services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_ROLE_UNVERIFIED_ID=${DISCORD_ROLE_UNVERIFIED_ID}
      - DISCORD_ROLE_VERIFIED_ID=${DISCORD_ROLE_VERIFIED_ID}
      - DISCORD_ROLE_MEMBER_ID=${DISCORD_ROLE_MEMBER_ID}
      - DISCORD_ROLE_PRO_ID=${DISCORD_ROLE_PRO_ID}
      - DISCORD_CHANNEL_VERIFICATION_ID=${DISCORD_CHANNEL_VERIFICATION_ID}
      - DISCORD_CHANNEL_OFFICIAL_LINKS_ID=${DISCORD_CHANNEL_OFFICIAL_LINKS_ID:-1510828840161771631}
      - DISCORD_CHANNEL_RULES_ID=${DISCORD_CHANNEL_RULES_ID}
      - DISCORD_CHANNEL_FAQS_ID=${DISCORD_CHANNEL_FAQS_ID}
      - DISCORD_CHANNEL_CALLS_ID=${DISCORD_CHANNEL_CALLS_ID}
      - DISCORD_CHANNEL_TARGETS_ID=${DISCORD_CHANNEL_TARGETS_ID}
      - DISCORD_CHANNEL_MEMBER_CHAT_ID=${DISCORD_CHANNEL_MEMBER_CHAT_ID}
      - DISCORD_CHANNEL_PRO_MEMBER_CHAT_ID=${DISCORD_CHANNEL_PRO_MEMBER_CHAT_ID}
      - PORTFUEL_APP_URL=${PORTFUEL_APP_URL}
      - BOT_API_KEY=${BOT_API_KEY}
      - DISCORD_BOT_WORKER_ID=${DISCORD_BOT_WORKER_ID}
    restart: unless-stopped

