import type { LegalSection } from "@/components/legal/LegalDocument";

export const PRIVACY_EFFECTIVE_DATE = "May 24, 2026";

export const PRIVACY_INTRO =
  "This Privacy Policy describes how PortFuel.pro (“PortFuel,” “we”) collects, uses, and shares information when you use our website and member workspace.";

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    title: "1. Information we collect",
    paragraphs: ["We collect information you provide and data generated by your use of the service:"],
    list: [
      "Account: username, display name, password hash, optional email, membership tier, and subscription status.",
      "Security: TOTP/authenticator secrets (stored encrypted), session tokens, and login attempt metadata for rate limiting.",
      "Content: trade calls, theses, comments, votes, and watchlist symbols you save.",
      "Billing: Stripe customer and subscription identifiers; payment details are processed by Stripe, not stored on our servers.",
      "Technical: IP address, browser type, and request logs needed to operate and secure the service.",
    ],
  },
  {
    title: "2. How we use information",
    paragraphs: ["We use collected data to:"],
    list: [
      "Authenticate you, enforce two-factor security, and gate paid features.",
      "Display your profile, calls, rankings, and community interactions.",
      "Process subscriptions, webhooks, and billing portal sessions via Stripe.",
      "Refresh market quotes, charts, and intel features tied to symbols you view.",
      "Prevent abuse, debug errors, and comply with legal obligations.",
    ],
  },
  {
    title: "3. Sharing",
    paragraphs: [
      "We do not sell your personal information. We share data only with service providers that help us run PortFuel (for example Supabase for database/auth, Vercel for hosting, Finnhub or similar providers for market data, and Stripe for payments) under contracts that limit their use.",
      "Member calls and display names may be visible to other members and, in limited form, on public marketing teasers as described on the site.",
    ],
  },
  {
    title: "4. Retention and security",
    paragraphs: [
      "We retain account and content data while your account is active and for a reasonable period afterward for backups, disputes, and legal compliance.",
      "We use industry-standard measures including HTTPS, hashed passwords, encrypted TOTP secrets, and role-based access controls. No method of transmission or storage is 100% secure.",
    ],
  },
  {
    title: "5. Your choices",
    paragraphs: [
      "You can update your display name in profile settings. Username changes are not supported after registration.",
      "Cancel recurring billing through Stripe Customer Portal from your profile. You may request account deletion by emailing support@portfuel.pro or opening a ticket in Help & support; some content may remain in backups for a limited time.",
    ],
  },
  {
    title: "6. Cookies and sessions",
    paragraphs: [
      "We use essential cookies (session) to keep you signed in. We do not use third-party advertising cookies on the member workspace.",
    ],
  },
  {
    title: "7. International users",
    paragraphs: [
      "If you access PortFuel from outside the United States, you understand that data may be processed in the U.S. or where our providers operate.",
    ],
  },
  {
    title: "8. Children",
    paragraphs: ["PortFuel is not directed to anyone under 18. We do not knowingly collect data from children."],
  },
  {
    title: "9. Changes",
    paragraphs: [
      "We may update this policy from time to time. The effective date at the top will change when we do. Material changes will be communicated when practicable.",
    ],
  },
  {
    title: "10. Contact",
    paragraphs: [
      "Privacy questions: email support@portfuel.pro or use Help & support in the workspace (portfuel.pro/dashboard/help).",
    ],
  },
];
